export const AssignmentsList = [
    {
        name: 'Homework 0',
        handoutURL: '../content/homeworks/hw0.pdf',
        out: '09/08 12:00 pm',
        due: '09/13 2:30 pm',
        latexTemplateURL: '',
        solutionURL: '',
    },
    {
        name: 'Homework 1',
        handoutURL: '../content/homeworks/hw1.pdf',
        out: '09/13 3:50 pm',
        due: '09/20 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw1.tex',
        solutionURL: '../content/homeworks/hw1_solution.pdf',
    },
    {
        name: 'Homework 2',
        handoutURL: '../content/homeworks/hw2.pdf',
        out: '09/20 3:50 pm',
        due: '09/27 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw2.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 3',
        handoutURL: '../content/homeworks/hw3.pdf',
        out: '09/27 5:00 pm',
        due: '10/04 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw3.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 4',
        handoutURL: '../content/homeworks/hw4.pdf',
        out: '10/04 3:50 pm',
        due: '10/11 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw4.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 5',
        handoutURL: '../content/homeworks/hw5.pdf',
        out: '10/11 3:50 pm',
        due: '10/18 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw5.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 6',
        handoutURL: '../content/homeworks/hw6.pdf',
        out: '10/25 3:50 pm',
        due: '11/01 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw6.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 7',
        handoutURL: '../content/homeworks/hw7.pdf',
        out: '11/1 3:50 pm',
        due: '11/10 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw7.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 8',
        handoutURL: '../content/homeworks/hw8.pdf',
        out: '11/10 3:50 pm',
        due: '11/17 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw8.tex',
        solutionURL: '',
    },
    {
        name: 'Homework 9',
        handoutURL: '../content/homeworks/hw9.pdf',
        out: '11/17 3:50 pm',
        due: '12/01 2:30 pm',
        latexTemplateURL: '../content/homeworks/hw9.tex',
        solutionURL: '',
    },
];